### ISSUE TITLE
Tutorial is loading too long

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlr-tutorial#31] opened 2015-12-14 14:01 UTC
I do not know much about html, java, etc. but every time I click on a page it takes some seconds until I can scroll down. I think that could be done faster. ;)

**Comment by berndbischl** [comment] 2015-12-14 14:55
that is strange. the tutorial is already rendered out in html? 
so there is no extra calculation or rendering being done when you request a page?

is it possible that some pics are just too large?

**Comment by zmjones** [comment] 2015-12-14 16:43
no the images are not very big. the only thing that could possibly be slow are the small bits of javascript, i.e., the syntax highlighter or mathjax. we have our own version of the former and are not using the cdn, and there isn't much math to be rendered. so i suspect it is either a latency issue with gh-pages or something specific to @PhilippPro.

**Comment by larskotthoff** [comment] 2015-12-14 17:03
The images are actually embedded into the HTML and "extracted" via Javascript I think. I notice a bit of a lag too, but it's not too bad.

**Comment by schiffner** [comment] 2015-12-15 10:45
For me it takes also like 1-2 seconds till I can scroll down. It's about the same for all pages in the tutorial, independent of the length of the page, the number of code boxes or plots. Only mathjax seems to take a little extra time.
(When I open the tutorial files I have on my computer instead of those from github, I can scroll immediately, so this speaks for the latency issue with gh-pages that Zach suspected?)

**Comment by berndbischl** [comment] 2015-12-15 11:36
Question is: can we do anything anything about this?

**Comment by larskotthoff** [comment] 2015-12-15 15:46
It sounds like the problem is the actual rendering of the page, which we could do something about (i.e. replacing all the "dynamic" content with static images). Whether that's easily possible is a different question and I suspect that the answer is no.

**Comment by zmjones** [comment] 2015-12-15 16:44
@larskotthoff I see image tags (e.g. [here](https://github.com/mlr-org/mlr-tutorial/blob/gh-pages/2.7/html/performance/index.html#L519)) in the html. where are they being extracted with JS?

[here](http://www.webpagetest.org/result/151215_CT_WR2/1/details/) is a little benchmark i ran on one of the pages. seems like the slowest thing by far is the search index.

**Comment by larskotthoff** [comment] 2015-12-15 17:30
@zmjones Sorry, what I meant is that the images are encoded as base64 blobs in the HTML -- you're right, they're not extracted with JS, but by the browser. There's some decoding going on there though. On pages with lots of images (e.g. https://mlr-org.github.io/mlr-tutorial/release/html/partial_prediction/index.html) this accounts for about half a second on my machine.

You're right that the search index is very heavy though. I'll have a look if we can make this lighter easily.

**Comment by larskotthoff** [comment] 2015-12-15 17:40
There doesn't seem to be an option for this in mkdocs.

**Comment by berndbischl** [comment] 2016-08-27 12:41
> There doesn't seem to be an option for this in mkdocs.

ok,  fine. closing.

**Closed as completed by berndbischl** 2016-08-27 12:41 UTC

**Comment by jakob-r** [comment] 2016-08-27 18:27
> [here](http://www.webpagetest.org/result/151215_CT_WR2/1/details/) is a little benchmark i ran on one of the pages. seems like the slowest thing by far is the search index.

Most of it is waiting for the first byte though and it's just 230KB of 1.4MB on your benchmarked website.
