### ISSUE TITLE
move everything one directory up

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr-tutorial#2] opened 2015-06-26 09:40 UTC
http://mlr-org.github.io/mlr-tutorial/tutorial/ is just to redundant.
http://mlr-org.github.io/mlr-tutorial/release/html/ is how it should look like.
Any thoughts?
I would just need an ok and a lock to change all links.

**Comment by schiffner** [comment] 2015-06-29 11:22
I'm not opposed, but would like to let @larskotthoff decide, because he built the directory structure.

**Comment by larskotthoff** [comment] 2015-06-29 17:01
Fine with me.

**Comment by jakob-r** [comment] 2015-07-01 07:24
I will do it now

**Comment by jakob-r** [comment] 2015-07-01 10:45
Okay - i am mainly finished - waiting for travis to pass

**Comment by schiffner** [comment] 2015-07-01 10:46
Big thanks!

**Comment by larskotthoff** [comment] 2015-07-02 02:47
Ok, for some reason this fails in Travis (see https://travis-ci.org/mlr-org/mlr-tutorial/builds/69224059). I can't reproduce this locally.

The commits break the published tutorial, so I've reverted everything for now -- this needs to work while useR is going on. All the changes are in a new branch gh-pages-move that we can come back to next week.

**Comment by larskotthoff** [comment] 2015-07-02 05:03
So the error seems to be completely unrelated -- Travis is and stays broken. I've pushed a hand-generated version so that the tutorial itself works at least.

I'm going to continue investigating what's happening next week (after useR) unless somebody has an idea what's going on here?

**Comment by schiffner** [comment] 2015-07-02 10:27
Sorry, was away last evening, otherwise I could have clarified things earlier: @jakob-r 's changes are indeed unrelated. Before failing, the travis build #69 worked, but ran into a 50 min error. I restarted it several times, but had no luck. I will go over the tutorial next week and see if I can make things cheaper. 

After installing mlr HEAD I can reproduce the _error in building the tutorial_ locally.
It's related to the latest changes in `plotThreshVsPerf`(l. 98 - 102 in https://github.com/berndbischl/mlr/blob/c6e7d591cbdba2703971bd851fc62ead33845628/R/generateThreshVsPerf.R: use measure names for annotating the plots).
For the custom measure `credit.costs` calling `get` (in l. 99) causes the error. Apparently, when building the tutorial, `credit.costs` is not in the environment where `get` is looking.

Unfortunately, at the moment I can't reproduce _the error itself_.

**Comment by berndbischl** [comment] 2015-07-02 11:19
Who wrote that code there? I mean using a "get" is like saying "Please R, hurt me, now".
Why is that needed?

**Comment by jakob-r** [comment] 2015-07-02 11:23
Please discuss what is broken not because of the directory change in another thread.

**Comment by berndbischl** [comment] 2015-07-02 11:29
Yes, we should keep issues separate. But I guess this might also be something rather for email. Let me just say one thing here, which I will repeat again in an email. Stuff like get() CANNOT be used, expect it is unavoidable. We need a proper programming style, somebody cannot write code ala "well it works on my machine, here, now".

**Comment by zmjones** [comment] 2015-07-02 12:37
I think that maybe was the commit that lars merged because he thought it was only the 50 minute error? You should revert that commit though!

**Comment by larskotthoff** [comment] 2015-07-02 23:51
Ok, all of that should be fixed now. I'll wait until after useR to reinstate Jakob's changes :)

**Comment by larskotthoff** [comment] 2015-07-03 18:17
I will do this now.

**Comment by larskotthoff** [comment] 2015-07-03 19:28
Done.

**Closed as completed by larskotthoff** 2015-07-03 19:28 UTC

**Comment by schiffner** [comment] 2015-07-03 22:26
Thanks, Lars.
I also did this:

9e7f1b25af747e84601e967a19f4c686f1d8f0b8

https://github.com/berndbischl/mlr/commit/86d6a4d36e054720200941b6e39e67e7c560a30a

I hope we got everything now. :)

**Comment by larskotthoff** [comment] 2015-07-03 22:28
Thanks!
